name: Full Trending Models Pipeline

on:
  schedule:
    - cron: "0 7 * * 1-5" # Runs Mon to Fri at 9:00 AM CEST / 8:00 AM CET
  workflow_dispatch: # Allows manual triggering

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

    - name: Set up Python
      uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c  # v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Step 1 - Parse Trending Models
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: python 01_parse_trending_models.py

    - name: Step 2 - Custom Code Repos
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: python 04_upstream_transformers.py

    # - name: Step 2 - Process Code for HF Jobs
    #   env:
    #     SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
    #     HF_TOKEN: ${{ secrets.HF_TOKEN }}
    #   run: python 02_process_code.py

    # - name: Step 3 - Execute code using HF Jobs
    #   env:
    #     SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
    #     HF_TOKEN: ${{ secrets.HF_TOKEN }}
    #   run: python 03_run_jobs.py
